ECommerce.WebUI/Models/CartSummaryViewModel.cs
using ECommerce.Entities.Concrete;

namespace ECommerce.WebUI.Models
{
    public class CartSummaryViewModel
    {
        public Cart? Cart { get; set; }
    }
}

ECommerce.WebUI/Controllers/CartController.cs
using ECommerce.Business.Abstract;
using ECommerce.Entities.Concrete;
using ECommerce.WebUI.Models;
using ECommerce.WebUI.Services;
using Microsoft.AspNetCore.Mvc;

namespace ECommerce.WebUI.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartSessionService _cartSessionService;
        private readonly IProductService _productService;
        private readonly ICartService _cartService;

        public CartController(ICartSessionService cartSessionService, IProductService productService, ICartService cartService)
        {
            _cartSessionService = cartSessionService;
            _productService = productService;
            _cartService = cartService;
        }

        public async Task<IActionResult> AddToCart(int productId,int page,int category)
        {
            var productToBeAdded=await _productService.GetByIdAsync(productId);
            var cart = _cartSessionService.GetCart();
            
            _cartService.AddToCart(cart, productToBeAdded);
            _cartSessionService.SetCart(cart);

            TempData.Add("message", String.Format("Your Product, {0} was added successfully to cart", productToBeAdded.ProductName));
            return RedirectToAction("Index","Product",new {page=page,category=category});
        }

        public IActionResult List()
        {
            var cart=_cartSessionService.GetCart();
            var model = new CartListViewModel
            {
                Cart= cart
            };
            return View(model);
        }

        public IActionResult Remove(int productId) { 
            var cart=_cartSessionService.GetCart();
            _cartService.RemoveFromCart(cart,productId);
            _cartSessionService.SetCart(cart);
            TempData.Add("message", "Your product removed successfully from cart");
            return RedirectToAction("List");
        }

        public IActionResult Complete()
        {
            var shippingDetailViewModel = new ShippingDetailViewModel
            {
                ShippingDetails = new ShippingDetails()
            };
            return View(shippingDetailViewModel);
        }


        [HttpPost]
        public IActionResult Complete(ShippingDetailViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            TempData.Add("message", String.Format("Thank you {0} , you order is in progress", model.ShippingDetails.Firstname));
            return RedirectToAction("List");
        }

    }
}

ECommerce.WebUI/Views/Shared/Components/CartSummary/Default.cshtml
@model CartSummaryViewModel

<ul style="margin-left:-200px !important;" class="dropdown-menu" aria-labelledby="navbarDropdown">
    <li>
        <ul class="list-group">

            @foreach (var item in Model.Cart.CartLines)
            {
                <li class="list-group-item">
                    <a> @item.Product.ProductName <span class="badge bg-success p-2 rounded text-white">@item.Quantity</span> </a>
                </li>
            }
        </ul>
    </li>


    <li class="dropdown-divider"></li>

    <li class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">@Model.Cart.Total $</h5>
            <a class="btn btn-primary" asp-controller="Cart" asp-action="List">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                    <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                </svg>
                Go to cart details
            </a>
        </div>
    </li>


</ul>